server:
  port: 8084
  servlet:
    context-path: "/engine/"
    
spring:
  application:
    name: gps-engine-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gpsms-engine
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    open-in-view: false
  output:
    ansi:
      enabled: always
      
logging:
  level:
    root: info
    '[org.springframework.web]': debug
    '[org.hibernate]': info
    '[com.codetruck.gps]': info

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost