server:
  port: 8080
    
spring:
  application:
    name: gps-api-gateway
  cloud:
    gateway:
      routes:
        - id: gps-authuser-service
          uri: 
            lb://GPS-AUTHUSER-SERVICE
          predicates:
            - Path=/gps-authuser/**
        - id: gps-typification-service
          uri:
            lb://GPS-TYPIFICATION-SERVICE
          predicates:
            - Path=/gps-typification/**
        - id: gps-engine-service
          uri:
            lb://GPS-ENGINE-SERVICE
          predicates:
            - Path=/gps-engine/**
            
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
