server:
  port: 8086
  servlet:
    context-path: "/gps-typification/"
  
spring:
  application:
    name: gps-typification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gpsms-typification
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    open-in-view: false
  output:
    ansi:
      enabled: always

logging:
  level:
    root: info
    '[org.springframework.web]': debug
    '[org.hibernate]': info
    '[com.codetruck]': trace
    
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
