server:
  port: 8087
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gpsms-authuser
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
